### ISSUE TITLE
NullPointerException

### ISSUE THREAD

**Issue by andrepacak** [pluto-build/build-java#3]
I found another bug. It occurs if you pass a non-empty list of BuildRequest to JavaInput.
I will try to construct a simple example.

**Comment by andrepacak** [comment]
Just clone this repository: https://github.com/andiderp/build-java-bug-example
and call ./execute.sh -arg0 "srcfiles" -arg1 "targetclass"

**Comment by seba--** [comment]
Can you make this a self-contained example (without the GIT builder, etc.)? A few Java files and how to call the JavaBuilder would be perfect. And the error that you observed (including stack trace if possible).

**Comment by andrepacak** [comment]
Update the repository and removed the git builder and added a builder that creates and writes two .java files.

**Comment by seba--** [comment]
I fixed a bug in the Java builder that lead to strange behavior in combination with cyclic units. Mainly, the problem was that java.io.File.equals(...) distinguishes relative from absolute paths. This lead the JavaInput.equals method to fail, such that the cycle was handled wrongly. Adaptions to example code are here https://github.com/andiderp/build-java-bug-example/pull/1
